### ISSUE TITLE
FeatureRequest: Tappable Polygon

### ISSUE THREAD

**Issue by S-Man42** [OwnWeb/flutter_map_tappable_polyline#32] opened 2021-07-23 06:34 UTC
Since Polyline coloring is difficult, when you try to color the area of closed polylines (which makes them polygons). So in that case, a Polygon would be better. 

Do you think, a TappablePolygon implementation is possible?

**Comment by tuarrep** [comment] 2021-07-24 11:05
Duplicate of #1

**Closed by tuarrep** 2021-07-24 11:05 UTC
